// hub-web/src/main/webapp/app/security/registration.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { AuthenticationService } from 'app/security/authentication.service';
import { RegistrationRequest } from 'app/security/authentication.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { validOffsetDateTime } from 'app/common/utils';


@Component({
  selector: 'app-registration',
  imports: [CommonModule, ReactiveFormsModule, InputRowComponent],
  templateUrl: './registration.component.html'
})
export class RegistrationComponent {

  authenticationService = inject(AuthenticationService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  registrationForm = new FormGroup({
    email: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    password: new FormControl(null, [Validators.required, Validators.maxLength(72)]),
    firstName: new FormControl(null, [Validators.maxLength(255)]),
    lastName: new FormControl(null, [Validators.maxLength(255)]),
    resetPasswordToken: new FormControl(null, [Validators.maxLength(255)]),
    resetPasswordTokenSentAt: new FormControl(null, [validOffsetDateTime]),
    emailConfirmationToken: new FormControl(null, [Validators.maxLength(255)]),
    emailConfirmationTokenSentAt: new FormControl(null, [validOffsetDateTime]),
    emailConfirmed: new FormControl(false),
    countryCode: new FormControl(null, [Validators.maxLength(10)]),
    phone: new FormControl(null, [Validators.maxLength(50)]),
    phoneConfirmationToken: new FormControl(null, [Validators.maxLength(255)]),
    phoneConfirmationTokenSentAt: new FormControl(null, [validOffsetDateTime]),
    phoneConfirmed: new FormControl(false),
    profileImageUrl: new FormControl(null, [Validators.maxLength(255)]),
    isActive: new FormControl(false),
    isLocked: new FormControl(false)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      registrationSuccess: $localize`:@@registration.register.success:Your registration is complete. You may now login.`,
      USER_EMAIL_UNIQUE: $localize`:@@registration.register.taken:This account is already taken. Please login.`
    };
    return messages[key];
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.registrationForm.markAllAsTouched();
    if (!this.registrationForm.valid) {
      return;
    }
    const data = new RegistrationRequest(this.registrationForm.value);
    this.authenticationService.register(data)
        .subscribe({
          next: () => this.router.navigate(['/login'], {
            state: {
              msgSuccess: this.getMessage('registrationSuccess')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.registrationForm, this.getMessage)
        });
  }

}

<h1 class="grow text-3xl md:text-4xl font-medium mb-8" i18n="@@registration.register.headline">Registration</h1>
<form [formGroup]="registrationForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="registrationForm" field="email" i18n-label="@@registrationRequest.email.label" label="Email" />
    <app-input-row [group]="registrationForm" field="password" rowType="password" i18n-label="@@registrationRequest.password.label" label="Password" />
    <app-input-row [group]="registrationForm" field="firstName" i18n-label="@@registrationRequest.firstName.label" label="First Name" />
    <app-input-row [group]="registrationForm" field="lastName" i18n-label="@@registrationRequest.lastName.label" label="Last Name" />
    <app-input-row [group]="registrationForm" field="resetPasswordToken" i18n-label="@@registrationRequest.resetPasswordToken.label" label="Reset Password Token" />
    <app-input-row [group]="registrationForm" field="resetPasswordTokenSentAt" i18n-label="@@registrationRequest.resetPasswordTokenSentAt.label" label="Reset Password Token Sent At" />
    <app-input-row [group]="registrationForm" field="emailConfirmationToken" i18n-label="@@registrationRequest.emailConfirmationToken.label" label="Email Confirmation Token" />
    <app-input-row [group]="registrationForm" field="emailConfirmationTokenSentAt" i18n-label="@@registrationRequest.emailConfirmationTokenSentAt.label" label="Email Confirmation Token Sent At" />
    <app-input-row [group]="registrationForm" field="emailConfirmed" rowType="checkbox" i18n-label="@@registrationRequest.emailConfirmed.label" label="Email Confirmed" />
    <app-input-row [group]="registrationForm" field="countryCode" i18n-label="@@registrationRequest.countryCode.label" label="Country Code" />
    <app-input-row [group]="registrationForm" field="phone" i18n-label="@@registrationRequest.phone.label" label="Phone" />
    <app-input-row [group]="registrationForm" field="phoneConfirmationToken" i18n-label="@@registrationRequest.phoneConfirmationToken.label" label="Phone Confirmation Token" />
    <app-input-row [group]="registrationForm" field="phoneConfirmationTokenSentAt" i18n-label="@@registrationRequest.phoneConfirmationTokenSentAt.label" label="Phone Confirmation Token Sent At" />
    <app-input-row [group]="registrationForm" field="phoneConfirmed" rowType="checkbox" i18n-label="@@registrationRequest.phoneConfirmed.label" label="Phone Confirmed" />
    <app-input-row [group]="registrationForm" field="profileImageUrl" i18n-label="@@registrationRequest.profileImageUrl.label" label="Profile Image Url" />
    <app-input-row [group]="registrationForm" field="isActive" rowType="checkbox" i18n-label="@@registrationRequest.isActive.label" label="Is Active" />
    <app-input-row [group]="registrationForm" field="isLocked" rowType="checkbox" i18n-label="@@registrationRequest.isLocked.label" label="Is Locked" />
    <input type="submit" i18n-value="@@registration.register.headline" value="Registration" class="inline-block text-white bg-blue-600 hover:bg-blue-700 focus:ring-blue-300  focus:ring-4 rounded px-5 py-2 mt-6" />
</form>

// hub-web/src/main/webapp/app/security/registration.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { RegistrationRequest } from 'app/security/authentication-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    email: yup.string().emptyToNull().max(255).required(),
    password: yup.string().emptyToNull().max(72).required(),
    firstName: yup.string().emptyToNull().max(255),
    lastName: yup.string().emptyToNull().max(255),
    resetPasswordToken: yup.string().emptyToNull().max(255),
    resetPasswordTokenSentAt: yup.string().emptyToNull().offsetDateTime(),
    emailConfirmationToken: yup.string().emptyToNull().max(255),
    emailConfirmationTokenSentAt: yup.string().emptyToNull().offsetDateTime(),
    emailConfirmed: yup.bool(),
    countryCode: yup.string().emptyToNull().max(10),
    phone: yup.string().emptyToNull().max(50),
    phoneConfirmationToken: yup.string().emptyToNull().max(255),
    phoneConfirmationTokenSentAt: yup.string().emptyToNull().offsetDateTime(),
    phoneConfirmed: yup.bool(),
    profileImageUrl: yup.string().emptyToNull().max(255),
    isActive: yup.bool(),
    isLocked: yup.bool()
  });
}

export default function Registration() {
  const { t } = useTranslation();
  useDocumentTitle(t('authentication.login.headline'));

  const navigate = useNavigate();

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const getMessage = (key: string) => {
    const messages: Record<string, string> = {
      USER_EMAIL_UNIQUE: t('registration.register.taken'),
      USER_EXTERNAL_LOGIN_UNIQUE: t('exists.user.externalLogin')
    };
    return messages[key];
  };

  const register = async (data: RegistrationRequest) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/register', data);
      navigate('/login', {
            state: {
              msgSuccess: t('registration.register.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t, getMessage);
    }
  };

  return (<>
    <h1 className="grow text-3xl md:text-4xl font-medium mb-8">{t('registration.register.headline')}</h1>
    <form onSubmit={useFormResult.handleSubmit(register)} noValidate>
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="email" required={true} />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="password" required={true} type="password" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="firstName" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="lastName" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="resetPasswordToken" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="resetPasswordTokenSentAt" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="emailConfirmationToken" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="emailConfirmationTokenSentAt" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="emailConfirmed" type="checkbox" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="countryCode" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="phone" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="phoneConfirmationToken" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="phoneConfirmationTokenSentAt" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="phoneConfirmed" type="checkbox" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="profileImageUrl" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="isActive" type="checkbox" />
      <InputRow useFormResult={useFormResult} object="registrationRequest" field="isLocked" type="checkbox" />
      <input type="submit" value={t('registration.register.headline')} className="inline-block text-white bg-blue-600 hover:bg-blue-700 focus:ring-blue-300  focus:ring-4 rounded px-5 py-2 mt-6" />
    </form>
  </>);
}
